### ISSUE TITLE
p-values for effect measures

### ISSUE THREAD

**Issue by sarahirvin0** [epi-zen/interactionR#1]
Great package - the option to output p-values for each measure of effect modification would be helpful!

**Comment by epi-zen** [comment]
Hi @sarahirvin0. The package is now updated to allow the option of outputting p-values. This is done with the _interactionR_table()_ function. This includes the p-values for the individual and joint effect estimates and the stratum-specific effect estimates. However, out of the three methods to compute CI of the interaction measures (RERI e.t.c), currently, only the p-values of the interaction measures computed with the delta method can be outputted.

**Comment by sarahirvin0** [comment]
Thanks so much! Great!

It looks as if the interactionR_table function doesn't recognize the p.value option (after checking for updates/re-installing the package). Any thoughts?

**Comment by epi-zen** [comment]
Hello, @sarahirvin0  that's because it is not yet on CRAN. The submission team at CRAN is on vacation till Sep 1, 2021.
During this time not packages can be submitted, except until Sept. 1 when I will make the next attempt to resubmit the new version. However, in the meantime, you can install this development from GitHub using:

`# install.packages("devtools")
devtools::install_github("epi-zen/interactionR")
`

works the same

**Comment by epi-zen** [comment]
Hello, @sarahirvin0  the new version is now on CRAN! When you re-install the package now in R the interactionR_table should work as it should
