### ISSUE TITLE
Application to cox proportional model 

### ISSUE THREAD

**Issue by beiwo07** [epi-zen/interactionR#9]
Hi, thanks for this great package! 
I'm using this package with my proportional hazard model and found that the P-value calculations for the interaction HRs ratio are off, as they are different from what's in the model output. However, the 95% CI and coefficients are consistent with what's in the model output. 
For the CI and p value of the RERI, I have no easy way to verify whether they are correctly estimated. Could you provide some insights in terms of whether the package can be applied to cox proportional hazard model? 
Thank you!

**Comment by epi-zen** [comment]
Hi @beiwo07 

Although the package is optimized for GLM, it is very compatible with survival models. Yet, once in a while you find a bug like this when using it with survival models.

For the most part, most of the reported pvalues are directly extracted from the passed model. There is a difference in how the GLM outputs pvalues vs how the survival package does it. You have found a bug where the package was extracting the zvalue instead of the pvalue from a survival model based on these outputting differences (it extracts the correct parameters from a GLM). I have now updated the package to fix this. To use it, you can install this development version from this Github repo. I will push the update to CRAN as soon as possible.

For the pvalues that are estimated afresh by the package, these are estimated from the confidence intervals as described in Altman & Bland 2011 How to Obtain the P Value from a Confidence Interval (BMJ 2011;343:d2304; https://doi.org/10.1136/bmj.d2304). As you rightly noted, all the CIs are consistent and they are all Wald-type CIs.

For the CI and pvalue of RERI, SI, AP. The CIs are either computed by the delta method, 'MOVER', or bootstrapping methods (See their respective citations for the estimation procedures). Out of these three methods, the package can only output pvalues for the delta method (i.e., the pvalues for RERI,SI,AP are based on the delta method, if you select the two other methods for the estimation of the RERI CI, the outputted pvalues will be NA)

**Comment by beiwo07** [comment]
Thanks so much!
